# .build.yaml
# Sourcehut build manifest for this code base.
# Documentation: <URL:https://man.sr.ht/builds.sr.ht/manifest.md>.
---
image: debian/bookworm
packages:
  - file
  - git-extras
  - make
  - python3-pip
  - python3-venv
environment:
  VIRTUAL_ENV: venv
  REPO_NAME: changelog-chug
sources:
  - https://git.sr.ht/~bignose/changelog-chug
tasks:
  - setup: |
      python3 -m venv "$VIRTUAL_ENV"
      source "$VIRTUAL_ENV"/bin/activate
      cd "$REPO_NAME"/
      python3 -m pip install --editable .[test]
  - check: |
      source "$VIRTUAL_ENV"/bin/activate
      make --directory "$REPO_NAME"/ check
  - test: |
      source "$VIRTUAL_ENV"/bin/activate
      make --directory "$REPO_NAME"/ clean test-coverage
